## Copyright [2017-2018] UMR MISTEA INRA, UMR LEPSE INRA,                ##
##                       UMR AGAP CIRAD, EPI Virtual Plants Inria        ##
##                                                                       ##
## This file is part of the StatisKit project. More information can be   ##
## found at                                                              ##
##                                                                       ##
##     http://statiskit.rtfd.io                                          ##
##                                                                       ##
## The Apache Software Foundation (ASF) licenses this file to you under  ##
## the Apache License, Version 2.0 (the "License"); you may not use this ##
## file except in compliance with the License. You should have received  ##
## a copy of the Apache License, Version 2.0 along with this file; see   ##
## the file LICENSE. If not, you may obtain a copy of the License at     ##
##                                                                       ##
##     http://www.apache.org/licenses/LICENSE-2.0                        ##
##                                                                       ##
## Unless required by applicable law or agreed to in writing, software   ##
## distributed under the License is distributed on an "AS IS" BASIS,     ##
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or       ##
## mplied. See the License for the specific language governing           ##
## permissions and limitations under the License.                        ##

package:
  name: conda-tools
  version: "0.9.0"

source:
  path: ../../..

build:
  number: 0
  entry_points:
    - conda-download = conda_tools.cli:download
    - conda-release = conda_tools.cli:release

requirements:
  build:
    - python
    - python-toolchain
    - conda 4.3.30
    - conda-build 3.0.30
    - anaconda-client
  run:
    - python
    - {{ pin_compatible('conda', exact=True) }}
    - {{ pin_compatible('conda-build', exact=True) }}
    - {{ pin_compatible('anaconda-client', exact=True) }}
    - networkx

test:
  requires:
    - python-toolchain
  imports:
    - conda_tools
  source_files:                                
    - test/test_*.py
    - share/git/*
  commands:                                       
    - which conda-download  # [unix]
    - where conda-download  # [win]
    - conda download -h
    - which conda-release  # [unix]
    - where conda-release  # [win]
    - conda release -h
    - conda --help
    # - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and linux" [linux]
    # - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and osx"   [osx]
    # - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and win"   [win]

about:
  home: https://github.com/StatisKit/conda-tools
  license: Apache License 2.0
  summary: Multiple tools for easing the usage of Conda for developers

