package:
  name: conda-tools
  version: "0.9.0"

source:
  path: ../../..

build:
  number: 0
  entry_points:
    - conda-download = conda_tools.cli:download
    - conda-release = conda_tools.cli:release

requirements:
  build:
    - python {{ PY_VER }}
    - python-toolchain
    - conda
    - conda-build
    - anaconda-client
  run:
    - python {{ PY_VER }}
    - {{ pin_compatible('conda', exact=True) }}
    - {{ pin_compatible('conda-build', exact=True) }}
    - {{ pin_compatible('anaconda-client', exact=True) }}
    - networkx

test:
  requires:
    - python-toolchain
  imports:
    - conda_tools
  source_files:                                
    - test/test_*.py
    - share/git/*
  commands:                                       
    - which conda-download  # [unix]
    - where conda-download  # [win]
    - conda download -h
    - which conda-release  # [unix]
    - where conda-release  # [win]
    - conda release -h
    - conda --help
    # - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and linux" [linux]
    # - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and osx"   [osx]
    # - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and win"   [win]

about:
  home: https://github.com/StatisKit/conda-tools
  license: Apache License 2.0
  summary: Multiple tools for easing the usage of Conda for developers

