package:
  name: conda-download
  version: "0.9.0"

source:
  path: ../../..

build:
  number: 0
  entry_points:
    - conda-download = conda_download.cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - conda-build

test:
  commands:
    - which conda-download  # [unix]
    - where conda-download  # [win]
    - conda download -h
    - conda --help
  imports:
    - conda_download

outputs:
  - type: wheel
  - name: {{ PKG_NAME }}

about:
  home: https://github.com/StatisKit/conda-download
  license: Apache License 2.0
  summary: conda-download is a tool for downloading Conda dependencies of recipes.

